<?php

/**
 * Implements hook_form_FORM_ID_alter().
 * Form ID: media_add_upload_multiple
 * Media module form with Plupload (Find content > Media > Add file)
 * NOTE: eatlas_media_browser_plus_fixes module also define that hook
 */
function eatlas_branding_fields_form_media_add_upload_multiple_alter(&$form, &$form_state) {
	_eatlas_branding_fields_add_image_extra_fields($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Form ID: media_add_upload
 * Media module form without Plupload (Find content > Media > Add file)
 *     it's also the form when adding image from CKEditor.
 * NOTE: eatlas_media_browser_plus_fixes module also define that hook
 */
function eatlas_branding_fields_form_media_add_upload_alter(&$form, &$form_state) {
	_eatlas_branding_fields_add_image_extra_fields($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Form ID: media_internet_add
 * I don't know where this is used, but Media browser plus implement
 *     that hook so it is probably useful.
 * NOTE: eatlas_media_browser_plus_fixes module also define that hook
 */
function eatlas_branding_fields_form_media_internet_add_alter(&$form, &$form_state) {
	_eatlas_branding_fields_add_image_extra_fields($form, $form_state);
}

/**
 * Add some fields to the "Add file" window, in the media browser
 * module, to set value for all uploaded images.
 * See: modules/media_browser_plus/media_browser_plus.module
 * Form API reference:
 *     https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7
 */
function _eatlas_branding_fields_add_image_extra_fields(&$form, &$form_state) {
	// Add branding fields
	// NOTE: This module has a weight of 20, so the fields get
	//   positionned correctly. (see eatlas_commons_form_add_field)
	eatlas_commons_form_add_field($form, eatlas_commons_get_image_field($form, $form_state, EATLAS_BRANDING_FIELD_BRANDING));
	eatlas_commons_form_add_field($form, eatlas_commons_get_image_field($form, $form_state, EATLAS_BRANDING_FIELD_SUPPORTED_BRANDINGS));

	eatlas_branding_set_branding_default_values($form);

	if (function_exists('eatlas_media_browser_plus_fixes_reorder_default_fields')) {
		eatlas_media_browser_plus_fixes_reorder_default_fields($form);
	}

	if (function_exists('eatlas_media_browser_plus_fixes_move_fields_to_group')) {
		eatlas_media_browser_plus_fixes_move_fields_to_group($form);
	}

	$form['#submit'][] = '_eatlas_branding_fields_add_image_extra_fields_submit';
}


function _eatlas_branding_fields_add_image_extra_fields_submit($form, &$form_state) {
	// Save the values to the image
	$branding = $form_state['values'][EATLAS_BRANDING_FIELD_BRANDING];
	$supportedBrandings = $form_state['values'][EATLAS_BRANDING_FIELD_SUPPORTED_BRANDINGS];

	if ($branding !== NULL || $supportedBrandings !== NULL) {
		$fids = $form_state['redirect'][1]['query']['fid'];
		if (!is_array($fids)) {
			$fids = array($fids);
		}
		$media_entities = file_load_multiple($fids);

		foreach ($media_entities as $media) {
			if ($branding !== NULL) {
				$media->{EATLAS_BRANDING_FIELD_BRANDING} = $branding;
			}
			if ($supportedBrandings !== NULL) {
				$media->{EATLAS_BRANDING_FIELD_SUPPORTED_BRANDINGS} = $supportedBrandings;
			}
			file_save($media);
		}
	}
}

?>
